project:
  type: website
  output-dir: docs
  
website:
  title: "mycoolrepo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - extra_tab.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/EmilyRose2001/mycoolrepo.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Emily Persson"

format:
  html:
    theme: Morph
    toc: true

editor: source

